### ISSUE TITLE
What is Enable Mingebag variant

### ISSUE THREAD

**Issue by eargau** [IcyStarFrost/Zeta-Players#2]
Question:
what is Enable Mingebag variant?
pov: It no issue. A just Question

**Comment by IcyStarFrost** [comment]
In Playermodel Options, Mingebag variant turns every zeta into t-posing kleiners. In Map Wide Spawning Options, natural zetas have a chance to spawn as a t-posing kleiner.

**Comment by eargau** [comment]
thx
